### ISSUE TITLE
Marginaler ovanför rubriker på vanliga textsidor för liten

### ISSUE THREAD

**Issue by peterk** [Kungbib/frontend-guide#16]
Exempel: https://biografblad.kb.se/om/ - utrymmet mellan navbar och sidan kanske bör ökas något.

**Comment by oBlissing** [comment]
Just marginalen mellan navbar och content är sådant som bör ligga i ett custom stylesheet då det beror på om man har en jumbotron och om man har en fixed navbar osv.

Man kan tänka sig att man istället gör en container för hela headern och ger containern en marginal, men då kommer problemet att man inte kan göra navbaren sticky.

Vi diskuterade lite på på morgonen att vi borde ge exempel på vanliga overrides i stilguiden. Till och med i exempel-layoutsen från bootstrap så har de först länkat in bootstrap.css och sedan länkat in ett override-sylesheet, så det är nog rätt väg att gå.

**Comment by peterk** [comment]
Låter rimligt. Jag testimplementerar det på biografbladen.
