### ISSUE TITLE
Exempel dropdownlista i 7.7.1

### ISSUE THREAD

**Issue by JeanetteBendelin** [Kungbib/frontend-guide#37]

**Comment by oBlissing** [comment]
~~Behöver vi det?~~

~~"Undvik dropdownlistor i formulär, använd checkboxar eller radioknappar istället."~~

Såg nu #36.

**Comment by JeanetteBendelin** [comment]
Goodie. Med combobox menar jag alltså: https://github.com/danielfarrell/bootstrap-combobox
