### ISSUE TITLE
länk till visualisering av data

### ISSUE THREAD

**Issue by JeanetteBendelin** [Kungbib/frontend-guide#49]
https://www.gov.uk/service-manual/user-centred-design/data-visualisation.html

**Comment by JeanetteBendelin** [comment]
Kommer kika mer på det här under Swepub-arbetet.

**Comment by oBlissing** [comment]
Exempel på visualisering från bootstrap
http://themes.getbootstrap.com/products/marketing?variant=4465241797
http://themes.getbootstrap.com/products/dashboard?variant=3943163717
