### ISSUE TITLE
links for downloading files should open in new window

### ISSUE THREAD

**Issue by JeanetteBendelin** [Kungbib/frontend-guide#54]

**Comment by oBlissing** [comment]
Håller med. Om man läser på lite här så bör man vara försiktig med att öppna nya fönster, men jag anser att just nedladdning av filer är avsides från vanlig navigering och bör göras i nytt fönster för att inte förstöra arbetsflödet.

http://www.w3.org/TR/WCAG20-TECHS/G200.html

**Comment by JeanetteBendelin** [comment]
Förtydligade i texten. Kika gärna och feedbacka.
