### ISSUE TITLE
Linjera menyn

### ISSUE THREAD

**Issue by JeanetteBendelin** [Kungbib/frontend-guide#62]
Jag tänker att det blir tydligast om undernivå 1 är linjerad med den övergripande nivån, och indrag enbart på undernivå 2. Alltså: 
1
1.1.
     1.1.1.

**Comment by oBlissing** [comment]
Har också gått i de tankarna. Testar så får vi avgöra.

**Comment by oBlissing** [comment]
Templatesen saknar klasser för de olika djupen i menysystemet, vilket är rätt lustigt eftersom de har klasser för det ändamålet i själva innehållet. Har lämnat en issue på kss-node projektet.
