### ISSUE TITLE
Align i horisontella formulär

### ISSUE THREAD

**Issue by Jokez80** [Kungbib/frontend-guide#81]
Vi upplevde det som att labeln bredvid ett formulärfält låg lite "off" mot själva fältet. Detta var för ett halvår sedan så kanske är fixat nu?

**Comment by oBlissing** [comment]
Kan du se om felet existerar i exemplen på denna sidan?
http://kungbib.github.io/frontend-guide/section-6.html

**Comment by oBlissing** [comment]
Stänger denna issuen eftersom den varit inaktiv väldigt länge.
